config:
  python:
    version: 3.5.2
    pip_version: 8.1.1
    # Invoke is currently pinned by this bug:
    #   https://github.com/pyinvoke/invoke/issues/345
    invoke_version: 0.12.2

  node:
    version: 4.5.0

  ruby:
    version: 2.3.1
    bundler_version: 1.13.1

  docker:
    cmd_bash_macos: /bin/bash
    cmd_dockermachine_macos: /usr/local/bin/docker-machine

    cmd_bash_windows: C:/Program Files/Git/bin/bash
    cmd_dockermachine_windows: C:/Program Files/Docker Toolbox/docker-machine.exe

    travis:
      version: 1.11.2-0~trusty
      compose_version: 1.8.0-rc1
      compose_up_delay: 60

  readme:
    working_directory: c:\devel\web-jekyll-base
    working_directory_mac: ~/Desktop/web-jekyll-base

    node_versions:
      - version: 4.5.0
        installer_url: https://nodejs.org/dist/v4.5.0/node-v4.5.0-x64.msi

    python_versions:
      - version: 3.5.2
        installer_url: https://www.python.org/ftp/python/3.5.2/python-3.5.2.exe
        install_path: c:\Python35
        virtual_environment_name: env35
        requirements_name: requirements3.txt

    ruby_versions:
      - version: 2.2.3
        installer_url: https://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.2.3.exe
        install_path: c:\Ruby223
        installer_devkit_url: https://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe
        install_devkit_path: c:\RubyDevKit
      - version: 2.3.1
        installer_url: https://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.3.1.exe
        install_path: c:\Ruby231
        installer_devkit_url: https://dl.bintray.com/oneclick/rubyinstaller/DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe
        install_devkit_path: c:\RubyDevKit

compile_config:
  entries:
    - in:  README.md.in
      out: README.md
    - in:  requirements3.in.in
      out: requirements3.in
    - in:  .travis.yml.in
      out: .travis.yml

compile_docker_localize:
  entries:
    - in:  tests/test-compose.yml
      out: tests/test-compose.localized.yml
    - in:  _config-test.yml
      out: _config-test.localized.yml
